services:
  db:
    image: postgres
    hostname: pg-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PG_USER: ${PG_USER}
    ports:
      - 5432:5432
    networks:
      - ride-registry-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  ride-repository:
    build: .
    ports:
      - 9991:9991
    environment:
      PORT: 9991
      POSTGRES_HOST: pg-db

    networks:
      - ride-registry-net
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  ride-registry-net:
