version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=EBikePassword
      - MARIADB_DATABASE=ebikedb
      - MARIADB_USER=EBikeApplication
      - MARIADB_PASSWORD=EBikePassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  ebike-service:
    image: matteoiorio/ebike-service:1.0.2
    ports:
      - "1926:1926"
    depends_on:
     - mariadb

volumes:
  mariadb_data:
