services:
  mariadb_test:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=EBikePassword
      - MARIADB_DATABASE=ebikedb_test
      - MARIADB_USER=EBikeApplication
      - MARIADB_PASSWORD=EBikePassword
    ports:
      - "9999:3306"
    healthcheck:
      test:  ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
    volumes:
      - mariadb_test:/var/lib/mysql

volumes:
  mariadb_test:
