scrape_configs:
  - job_name: 'vehicle-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['vehicle-service:1926']
