services:
  db:
    image: postgres
    hostname: pg-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg_data/init_db.sql:/docker-entrypoint-initdb.d/init.sql

    # ports:
    #   - 5432:5432

    networks:
      - user-service-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  user-service:
    build: .
    ports:
      - 11000:11000
    environment:
      PORT: 11000
      POSTGRES_HOST: pg-db

    networks:
      - user-service-net

    depends_on:
      db:
        condition: service_healthy
networks:
  user-service-net:
