services:
  ride-service:
    build: .
    hostname: ride-service
    ports:
      - 9990:9990
    env_file:
      ../.env
    networks:
      service-net:

networks:
  service-net:
    external: true

